baseURL = "https://tranindigo.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"

[params]
  customCss = [
    "css/style.css",
    "css/font-awesome.min.css",
    "css/grid.css",
    "css/materialize.min.css"
  ]
  customJS = [
    "js/jquery-2.1.1.min.js",
    "js/materialize.js",
    "js/modernizr.js",
    "js/scrollReveal.min.js",
    "js/footer-reveal.min.js",
    "js/grid.js",
    "js/init.js"
  ]